### ISSUE TITLE
Adding documentation to the README

### ISSUE THREAD

**Issue by dbalatero** [neovim/lua-client#52]
Hi – this library is missing useful beginner documentation that I've had to derive from trawling through test cases and source code.

There was a request for docs in #22 5 years ago, but it was closed as "the library is not sufficient for end users".

There was also a request for docs in #33 3 years ago, but it was closed as "this is used by all 3500+ tests in nvim", e.g. "just read the tests".

I think it's time for some introductory documentation, and I'm happy to write up what I've discovered so far, if you're willing to accept patches. I think at this point, if there are 3500 tests using this library, there exists at least some semblance of a stable API that is worth at least giving some introductory text on. If the API is not stable, you'll end up rewriting 3500+ tests in Neovim, so I just don't see it breaking so hard that documentation should be kept close to the vest.

What do you think? I'm happy to contribute to the docs as the first step.

**Comment by dbalatero** [comment]
At the very least, documenting:

* opening a new session
* closing a new session
* how to correctly use blocking `:request()`
* how to get events back when using blocking requests
* how to correctly use the async `:run()` / `:stop()` / `:request()` functions
* how to get event notifications with async calls

other topics:
* why you'd use sockets vs stdio vs tcp
* a few real world recipes (i have some ready to go)

**Comment by justinmk** [comment]
> There was also a request for docs in #33 3 years ago, but it was closed as "this is used by all 3500+ tests in nvim", e.g. "just read the tests".

yeah that's still the case. But some brief docs outlining usage are welcome, please send a PR for the readme.
