### ISSUE TITLE
Please use the HTTP(S) repo url in the rockspec file

### ISSUE THREAD

**Issue by OptiverTimAll** [neovim/lua-client#9]
Many people behind corporate firewalls cannot connect to the outside world via SSH (`git://`), so it would be much appreciated if you could update the rockspec file to change the source URL to `https://github.com/neovim/lua-client.git` (or possibly just http, until [luarocks support for HTTPS](https://github.com/keplerproject/luarocks/pull/350) is widespread).

**Comment by tarruda** [comment]
Could you send a PR with the required change?

**Comment by OptiverTimAll** [comment]
I'm afraid my employer won't allow me to create a PR for this change, despite how simple it would be.

**Comment by fwalch** [comment]
Fixed by #10.
